name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Install just
      uses: kodeshack/action-install-gh-release@v1
      with:
        owner: casey
        repo: just
        version: '1.35.0'
        test: just --version
    - uses: actions/checkout@v4
    - name: Lint
      run: |
        just lint-ci
    - name: Publish Lint Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: "Lint Results"
        files: |
          lint.junit.xml

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Install just
      uses: kodeshack/action-install-gh-release@v1
      with:
        owner: casey
        repo: just
        version: '1.35.0'
        test: just --version
    - uses: actions/checkout@v4
    - name: Run Tests
      run: |
        just test-ci github-actions
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        check_name: "Test Results"
        files: |
          test.junit.xml
